# Generated by Django 5.2.7 on 2025-10-01 17:21

import display.models
import display.storage
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='screen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screen_number', models.CharField(choices=[('1', 'Screen 1'), ('2', 'Screen 2'), ('3', 'Screen 3'), ('4', 'Screen 4')], default='1', help_text='Select screen', max_length=10)),
                ('video_file', models.FileField(storage=display.storage.OverwriteStorage(), upload_to=display.models.video_storage_directory, validators=[django.core.validators.FileExtensionValidator(['mp4'])])),
            ],
        ),
    ]
